<div data-dojo-type="dojo/store/Memory" data-dojo-id="navTreeStore">
	
	<script type="dojo/method">
        this.setData(<?=json_encode($this->tree_data);?>);
    </script>
    
    <script 
    	type="dojo/method" 
    	data-dojo-event="getChildren" 
    	data-dojo-args="object">
        return object.children || [];
    </script>
</div>

<div 
	data-dojo-type="dijit/tree/ObjectStoreModel" 
	data-dojo-id="navTreeModel" 
	data-dojo-props="store: navTreeStore, query: {id: 'root'}">
	
    <script 
    	type="dojo/method" 
    	data-dojo-event="mayHaveChildren" 
    	data-dojo-args="item">
        return "children" in item;
    </script>
</div>

<div 
	data-dojo-type="dijit/Tree" 
	id="main-sindnav-tree" 
	data-dojo-props="model: navTreeModel, showRoot: false">
	
	<script 
		type="dojo/method" 
		data-dojo-event="getIconClass" 
		data-dojo-args="item, opened">
        if( typeof item.icon == 'string')
        {
            return item.icon;
        }
        return ;
    </script>
	
</div>